batch_size: 5
image_width: 256
image_height: 256
image_depth: 3
pic_num_each_gif:
robot_configuration_num: 11

network: 
    im_conv_1: 
        type: 'conv'
        kernel_size: 3
        out_channel: 64
        stride: 1
    im_conv_2: 
        type: 'conv'
        kernel_size: 3
        out_channel: 64
        stride: 2
    im_conv_3: 
        type: 'conv'
        kernel_size: 3
        out_channel: 64
        stride: 2
    im_conv_4: 
        type: 'conv'
        kernel_size: 3
        out_channel: 32
        stride: 2
    im_conv_5: 
        type: 'conv'
        kernel_size: 3
        out_channel: 32
        stride: 2
        spatial_softmax:
    im_fc_1:
        type: 'fc'
        size: 256
        bias_transform: 20
        bias_transform_name: 'context'
        activation: 'leaky_relu'
    im_fc_2:
        type: 'fc'
        size: 128
        activation: 'leaky_relu'
    im_prediction:
        type: 'fc'
        size: 10
        activation: