batch_size: 5
image_width: 128
image_height: 128
image_depth: 3
pic_num_each_gif:
robot_configuration_num: 14

network: 
    im_conv_1: 
        type: 'conv'
        kernel_size: 3
        out_channel: 30
        stride: 2
    im_conv_2: 
        type: 'conv'
        kernel_size: 3
        out_channel: 30 
        stride: 2
    im_conv_3: 
        type: 'conv'
        kernel_size: 3
        out_channel: 30
        stride: 2
    im_fc_1:
        type: 'fc'
        size: 200
        bias_transform: 10
        bias_transform_name: 'context'
    im_fc_2:
        type: 'fc'
        size: 200
    im_prediction:
        type: 'fc'
        size: 10
    
