batch_size: 32
image_width: 240
image_height: 240
extra_width: 120
extra_height: 120
image_depth: 3
in_channel: 12
pics_each_gif:
robot_feedback_num: 11

network: 
    im_conv_1: 
        type: 'conv'
        kernel_size: 7
        out_channel: 64
        stride: 2
    im_conv_2: 
        type: 'conv'
        kernel_size: 7
        out_channel: 64
        stride: 2
    im_conv_3: 
        type: 'conv'
        kernel_size: 5
        out_channel: 32
        stride: 1
    im_conv_4: 
        type: 'conv'
        kernel_size: 5
        out_channel: 32
        stride: 1
        spatial_softmax:

network_ext:
    im_conv_1: 
        type: 'conv'
        kernel_size: 3
        out_channel: 16
        stride: 2
    im_conv_2: 
        type: 'conv'
        kernel_size: 3
        out_channel: 32
        stride: 2
    im_conv_3: 
        type: 'conv'
        kernel_size: 3
        out_channel: 48
        stride: 2
    im_conv_4: 
        type: 'conv'
        kernel_size: 3
        out_channel: 64
        stride: 2

network_con:
    im_fc_1:
        type: 'fc'
        size: 4096
        activation: 'leaky_relu'
    im_fc_2:
        type: 'fc'
        size: 128
        bias_transform: 20
        bias_transform_name: 'context'
        activation: 'leaky_relu'
    im_fc_3:
        type: 'fc'
        size: 2048
        activation: 'leaky_relu'
    im_fc_4:
        type: 'fc'
        size: 1024
        activation: 'leaky_relu'
    im_prediction:
        type: 'fc'
        size: 10
        activation: 
